Download
KonradLinkowski/Voronoi pull request #7
Opened 2020-10-08 17:57 UTC by manisacharya

- Added new download button to download converted image

2020-10-08 17:58 UTC, manisacharya commented
Hey @KonradLinkowski, I tried this version, can you look at this version?

2020-10-09 10:49 UTC, KonradLinkowski requested changes
Just remove the `var`s

2020-10-09 10:49 UTC, KonradLinkowski commented on assets/css/style.css
> +.button {
Can you change the class name to be more meaningful? Like `.download-button`.

2020-10-09 10:49 UTC, KonradLinkowski commented on assets/js/voronoi.js
> +var button = document.getElementById('btn-download');
Don't use `var` please. You can use `const` in this case.

2020-10-09 10:49 UTC, KonradLinkowski commented on assets/js/voronoi.js
> +button.addEventListener('click', function (e) {
I would rather use arrow function here - it looks more readable

2020-10-09 10:49 UTC, KonradLinkowski commented on assets/js/voronoi.js
> +  var image = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
`const`
Nice solution btw :)

2020-10-09 13:07 UTC, manisacharya commented
@KonradLinkowski I have updated code as per your suggestions and also resolved merge conflict.

2020-10-09 13:11 UTC, KonradLinkowski approved these changes

2020-10-09 13:11 UTC, merged